### model
model_name_or_path: $MODEL_PATH
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: sft_train
template: deepseek3
cutoff_len: 4096
max_new_tokens: 32768
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: $CKPT_PATH
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard
logging_dir: $TF_EVENTS_PATH
save_total_limit: 2

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
enabel_lighter_kernel: true
